version: '3'
services:
  db:
    image: mongo:4
  backend:
    image: node:14
    volumes:
      - ./backend:/backend
    ports:
      - 3000:3000
    command: bash -c "cd /backend && npm i && node app"
  frontend:
    image: nginx:1
    volumes:
      - ./frontend:/usr/share/nginx/html/
    ports:
      - 8000:80
