version: '3'
volumes:
  dados:
networks:
  banco:
  web:
services:
  db:
    image: postgres:12.4
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'pwd'
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./database/scripts:/scripts
      - ./database/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  frontend:
    image: nginx:1.19
    volumes:
      # Site
      - ./frontend:/usr/share/nginx/html/
      # Configuração do proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    networks:
      - web
    depends_on:
      - backend
  backend:
    image: python:3.8.5-buster
    volumes:
      # Aplicação
      - ./backend:/app
    working_dir: /app
    command: bash ./app.sh
    ports:
      - 8080:8080
    networks:
      - banco
      - web
    depends_on:
      - db
